apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: mytestapp1 
spec:
  replicas: 2 
  selector:
   matchLabels:
    app: mytestapp1 
  template:
    metadata: 
      labels:
        app: mytestapp1
    spec:
      containers:
      - name: mytestapp1
        image: sachinteli/docker:tagversion 
        ports:
        - containerPort: 8080
---
apiVersion: v1 
kind: Service 
metadata:
  name: mytestapp1-svc 
  labels:
    app: mytestapp1 
spec:
  type: LoadBalancer 
  ports:
  - protocol: TCP 
    port: 80
    targetPort: 8080 
  selector:
    app: mytestapp1
