apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-08-13T17:48:33Z"
  generation: 1
  labels:
    app: mytestapp1
  name: mytestapp1
  namespace: default
  resourceVersion: "133764"
  selfLink: /apis/apps/v1/namespaces/default/deployments/mytestapp1
  uid: 6c687966-2100-4479-9775-4c1ca6bfd265
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mytestapp1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mytestapp1
    spec:
      containers:
      - image: sachinteli/docker:latest
        imagePullPolicy: Always
        name: docker
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-08-13T17:48:42Z"
    lastUpdateTime: "2020-08-13T17:48:42Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-08-13T17:48:33Z"
    lastUpdateTime: "2020-08-13T17:48:42Z"
    message: ReplicaSet "mytestapp1-8578d9794" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
